apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.EnvConfigMapRef.name }}
  namespace: {{ .Release.Namespace }}
data:
  APP_NAME: {{ .Values.name }}
  APP_ENV: "production"
  APP_DEBUG: "true"
  APP_PORT: "443"
  APP_URL: "https://mohsen.k8s.photonicdata.science/"
  ASSET_URL: "https://mohsen.k8s.photonicdata.science/"
  LOG_CHANNEL: "stdout"
  DB_USERNAME: {{ .Values.postgresql.postgresqlUsername }}
  DB_CONNECTION: "pgsql"
  DB_HOST: {{ .Values.postgresql.host }}
  DB_PORT: "{{ .Values.postgresql.port }}"
  DB_DATABASE: {{ .Values.postgresql.postgresqlDatabase }}
  BROADCAST_DRIVER: "log"
  FILESYSTEM_DRIVER: "local"
  QUEUE_CONNECTION: "rabbitmq"
  RABBITMQ_HOST: {{ .Values.rabbitmq.host }}
  RABBITMQ_PORT: "{{ .Values.rabbitmq.port }}"
  RABBITMQ_USER: {{ .Values.rabbitmq.auth.username }}
  RABBITMQ_QUEUE: jobs
  SCOUT_DRIVER: meilisearch
  MEILISEARCH_HOST: {{ .Values.meilisearch.host }}
  SESSION_DRIVER: "redis"
  CACHE_DRIVER: "redis"
  REDIS_CLIENT: "predis"
  SESSION_LIFETIME: "120"
  MEMCACHED_HOST: "memcached"
  REDIS_HOST: {{ .Values.redis.host }}
  REDIS_PORT: "{{ .Values.redis.port }}"
  PUSHER_APP_ID: "null"
  PUSHER_APP_CLUSTER: "mt1"
  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  MAIL_MAILER: "smtp"
  MAIL_HOST: {{ .Values.smtp.host }}
  MAIL_PORT: "{{ .Values.smtp.port }}"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: {{ .Values.smtp.from }}
  MAIL_FROM_NAME: "VibspecDB"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BUCKET: "null"
  AWS_ENDPOINT: {{ .Values.minio.endpoint }}
  AWS_URL: {{ .Values.minio.baseUrl }}
  AWS_USE_PATH_STYLE_ENDPOINT: "false"
  GITLAB_REDIRECT_URI: {{ .Values.gitlab.redirectUrl }}
  GITLAB_BASE_URL: {{ .Values.gitlab.baseUrl }}
  KEYCLOAK_REDIRECT_URI: {{ .Values.keycloak.redirectUrl }}
  KEYCLOAK_BASE_URL: {{ .Values.keycloak.baseUrl }}
  KEYCLOAK_REALM: {{ .Values.keycloak.realm }}
  APP_KEY: {{  .Values.app.key }}
