apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.EnvSecretRefServices.name }}
  labels:
    {{- include "vibspecdb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.minio.enabled }}
  AWS_BUCKET: {{ .Values.minio.bucket |b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.minio.accessKey |b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.secretAccessKey |b64enc | quote }}
  {{- end -}}  
  {{- if .Values.gitlab.enabled }}
  GITLAB_KEY: {{ .Values.gitlab.accessKey |b64enc | quote }}
  GITLAB_SECRET: {{ .Values.gitlab.secretAccessKey |b64enc | quote }}
  {{- end -}}  
  {{- if .Values.keycloak.enabled }}
  KEYCLOAK_CLIENT_ID: {{ .Values.keycloak.clientId |b64enc | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.keycloak.clientSecret |b64enc | quote }}
  {{- end -}}  
  {{- if .Values.meilisearch.enabled }}
  MEILI_MASTER_KEY: {{ .Values.meilisearch.secretKey |b64enc | quote }}
  {{- end -}}  
