apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.EnvSecretRef.name }}
  labels:
    {{- include "mohsen.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.smtp.enabled }}
  MAIL_PASSWORD: {{ .Values.smtp.password |b64enc | quote }}
  {{- end -}}
  {{- if .Values.postgresql.enabled }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword |b64enc | quote }}
  {{- else if .Values.mysql.enabled }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword |b64enc | quote }}
  {{- end -}}
  {{- if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password |b64enc | quote }}
  {{- end -}}
  {{- if .Values.rabbitmq.enabled }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password |b64enc | quote }}
  {{- end -}}
